=== hugo-clems/al-2019/ACO/src/main/java/initialisation/initialisation.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="plateau">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="nom"/>
                <xs:element type="xs:byte" name="width"/>
                <xs:element type="xs:byte" name="heigth"/>
                <xs:element name="liste_agentite">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nid">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="nom"/>
                                        <xs:element name="position">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:byte" name="x"/>
                                                    <xs:element type="xs:byte" name="y"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:byte" name="fourmis"/>
                            <xs:element name="nourritures">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nourriture" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:byte" name="quantite"/>
                                                    <xs:element name="position">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:byte" name="x"/>
                                                                <xs:element type="xs:byte" name="y"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="obstacles" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="obstacle" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="position">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:byte" name="x"/>
                                                                <xs:element type="xs:byte" name="y"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hugo-clems/al-2019/ACO/src/main/java/initialisation/initialisation.xml
<?xml version="1.0" encoding="UTF-8"?>

<plateau xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="initialisation.xsd">
    <nom>Simulateur ACO</nom>
    <width>30</width>
    <heigth>30</heigth>
    <liste_agentite>
        <nid>
            <nom>Fourmil√®re</nom>
            <position>
                <x>20</x>
                <y>20</y>
            </position>
        </nid>
        <fourmis>2</fourmis>
        <nourritures>
            <nourriture>
                <quantite>50</quantite>
                <position>
                    <x>10</x>
                    <y>10</y>
                </position>
            </nourriture>
            <nourriture>
                <quantite>60</quantite>
                <position>
                    <x>15</x>
                    <y>15</y>
                </position>
            </nourriture>
        </nourritures>
        <obstacles>
            <obstacle>
                <position>
                    <x>5</x>
                    <y>5</y>
                </position>
            </obstacle>
            <obstacle>
                <position>
                    <x>5</x>
                    <y>6</y>
                </position>
            </obstacle>
        </obstacles>
    </liste_agentite>

</plateau>
